/* eslint-disable @typescript-eslint/no-unused-vars */
import { MigrationInterface, QueryRunner } from 'typeorm'

export class InsertIntoTableItem1734553586711 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    queryRunner.query(`
            INSERT INTO items (name, "imageId") VALUES
                ('Angular', 'angular.png'),
                ('Axios', 'axios.png'),
                ('Bootstrap', 'bootstrap.png'),
                ('C', 'c.png'),
                ('C#', 'csharp.png'),
                ('C++', 'cpp.png'),
                ('ChartJS', 'chartjs.png'),
                ('Clojure', 'clojure.png'),
                ('CSS', 'css.png'),
                ('D3JS', 'd3js.png'),
                ('Dart', 'dart.png'),
                ('Django', 'django.png'),
                ('Electron', 'electron.png'),
                ('Elixir', 'elixir.png'),
                ('Erlang', 'erlang.png'),
                ('ExpressJS', 'expressjs.png'),
                ('Flask', 'flask.png'),
                ('Flutter', 'flutter.png'),
                ('Fortran', 'fortran.png'),
                ('Go', 'go.png'),
                ('GraphQL', 'graphql.png'),
                ('Groovy', 'groovy.png'),
                ('Haskell', 'haskell.png'),
                ('HTML', 'html.png'),
                ('Ionic', 'ionic.png'),
                ('Java', 'java.png'),
                ('JavaScript', 'javascript.png'),
                ('JQuery', 'jquery.png'),
                ('Julia', 'julia.png'),
                ('Kotlin', 'kotlin.png'),
                ('Laravel', 'laravel.png'),
                ('Lisp', 'lisp.png'),
                ('Lodash', 'lodash.png'),
                ('MATLAB', 'matlab.png'),
                ('MongoDB', 'mongodb.png'),
                ('MySQL', 'mysql.png'),
                ('NestJS', 'nestjs.png'),
                ('NextJS', 'nextjs.png'),
                ('NumPy', 'numpy.png'),
                ('NuxtJS', 'nuxtjs.png'),
                ('Pandas', 'pandas.png'),
                ('Perl', 'perl.png'),
                ('PHP', 'php.png'),
                ('PostgreSQL', 'postgresql.png'),
                ('Python', 'python.png'),
                ('R', 'r.png'),
                ('React', 'react.png'),
                ('Redis', 'redis.png'),
                ('Redux', 'redux.png'),
                ('Ruby', 'ruby.png'),
                ('Ruby on Rails', 'rubyonrails.png'),
                ('Rust', 'rust.png'),
                ('Scala', 'scala.png'),
                ('Solidity', 'solidity.png'),
                ('Spring', 'spring.png'),
                ('Swift', 'swift.png'),
                ('Svelte', 'svelte.png'),
                ('TensorFlow', 'tensorflow.png'),
                ('ThreeJS', 'threejs.png'),
                ('TypeScript', 'typescript.png'),
                ('Vue', 'vue.png'),
                ('Zig', 'zig.png');`)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
